apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing-wordpress-com
generatorOptions:
  disableNameSuffixHash: true
bases:
  - ../../base
### Separated secret to use argocd ###
#secretGenerator:
#- name: kustomize-password
#  files:
#  - password=password.txt
#- name: docker-registry
#  files:
#   - '.dockerconfigjson=docker-registry.json'
#  type: kubernetes.io/dockerconfigjson
configMapGenerator:
- name: template-config
  literals:
  - WORDPRESS_DB_HOST=backend-db01
  - WORDPRESS_DB_NAME=wordpress
  - WORDPRESS_DB_USER=wordpress
  - MYSQL_DATABASE_WP=wordpress
  - MYSQL_USER_WP=wordpress
  - MYSQL_USER_MW=wordpress
  - MYSQL_DATABASE_MW=tips_wiki
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
images:
  - name: frontend-app01
    newName: wordpress
    newTag: "6.0.0-php8.1-apache"
  - name: backend-db01
    newName: mariadb
    newTag: "10.5"
  - name: frontend-app02
    newName: registry.gitlab.com/aimhigehrgg/repository/mediawiki-wiki
    newTag: "1.36.3"
  - name: backend-db02
    newName: mariadb
    newTag: "10.5"
  - name: frontend-static01
    newName: registry.gitlab.com/aimhigehrgg/repository/portfolio
    newTag: "1.0"
  - name: frontend-static02
    newName: registry.gitlab.com/aimhigehrgg/repository/maintenance
    newTag: "1.0"
replicas:
- name: frontend-app01
  count: 1
- name: backend-db01
  count: 1
- name: frontend-app02
  count: 1
- name: backend-db02
  count: 1
- name: frontend-static01
  count: 1
- name: frontend-static02
  count: 1
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: frontend-app01
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: backend-db01
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: backend-db02
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem