apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: www-aimhighergg-com
generatorOptions:
  disableNameSuffixHash: true
bases:
  - ../../base
### Separated secret to use argocd ###
#secretGenerator:
#- name: kustomize-password
#  files:
#  - password=password.txt
#- name: docker-registry
#  files:
#   - '.dockerconfigjson=docker-registry.json'
#  type: kubernetes.io/dockerconfigjson
configMapGenerator:
- name: template-config
  literals:
  - WORDPRESS_DB_HOST=backend-db01
  - WORDPRESS_DB_NAME=wordpress
  - WORDPRESS_DB_USER=wordpress
  - MYSQL_DATABASE_WP=wordpress
  - MYSQL_USER_WP=wordpress
  - MYSQL_USER_MW=wordpress
  - MYSQL_DATABASE_MW=tips_wiki
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
images:
  - name: frontend-app01
    newName: wordpress
    newTag: "6.0.0-php8.1-apache"
  - name: backend-db01
    newName: mariadb
    newTag: "10.5"
  - name: frontend-app02
    newName: registry.gitlab.com/aimhighergg/docker-registry/mediawiki-wiki
    newTag: "1.36.3"
  - name: backend-db02
    newName: mariadb
    newTag: "10.5"
  - name: frontend-static01
    newName: registry.gitlab.com/aimhighergg/docker-registry/portfolio
    newTag: "1.1"
  - name: frontend-static02
    newName: registry.gitlab.com/aimhighergg/docker-registry/maintenance
    newTag: "1.0"
  - name: frontend-static03
    newName: registry.gitlab.com/aimhighergg/docker-registry/flask-portfolio
    newTag: "1.0"
replicas:
- name: frontend-app01
  count: 1
- name: backend-db01
  count: 1
- name: frontend-app02
  count: 1
- name: backend-db02
  count: 1
- name: frontend-static01
  count: 1
- name: frontend-static02
  count: 1
- name: frontend-static03
  count: 1
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: frontend-app01
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: backend-db01
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: backend-db02
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: cluster-issuer
  spec:
    acme:
      email: aim4highergg@gmail.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: cluster-issuer-secret
      solvers:
      - http01:
          ingress:
            class: nginx
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-tls
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        deny 103.124.95.20/32;
        deny 137.184.96.81/32;
        deny 139.180.214.251/32;
        deny 142.132.194.96/32;
        deny 143.110.187.136/32;
        deny 165.22.202.244/32;
        deny 172.245.14.10/32;
        deny 176.99.3.198/32;
        deny 178.20.42.21/32;
        deny 18.133.60.229/32;
        deny 185.106.208.50/32;
        deny 185.161.210.69/32;
        deny 185.233.116.44/32;
        deny 185.233.36.233/32;
        deny 194.67.64.50/32;
        deny 195.123.212.109/32;
        deny 20.198.103.233/32;
        deny 212.224.88.227/32;
        deny 213.142.149.218/32;
        deny 23.111.202.207/32;
        deny 31.172.67.251/32;
        deny 31.31.196.115/32;
        deny 34.87.94.148/32;
        deny 34.96.143.131/32;
        deny 35.182.37.18/32;
        deny 36.91.100.149/32;
        deny 45.142.122.9/32;
        deny 45.148.123.130/32;
        deny 45.64.156.213/32;
        deny 45.64.156.214/32;
        deny 46.101.62.7/32;
        deny 47.241.15.216/32;
        deny 47.52.39.5/32;
        deny 47.88.78.84/32;
        deny 5.101.157.36/32;
        deny 5.23.50.61/32;
        deny 5.45.94.71/32;
        deny 5.9.115.229/32;
        deny 52.165.17.200/32;
        deny 62.171.129.97/32;
        deny 65.21.9.119/32;
        deny 68.183.85.239/32;
        deny 77.221.130.86/32;
        deny 77.244.214.239/32;
        deny 89.108.65.136/32;
        deny 89.252.178.177/32;
        deny 89.253.233.129/32;
        deny 92.204.134.137/32;
        deny 93.104.208.179/32;
        deny 95.217.149.71/32;
  spec:
    ingressClassName: nginx 
    tls:
    - hosts:
        - www.aimhighergg.com
      secretName: tls-secret
    rules:
    - host: www.aimhighergg.com
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: frontend-app01
              port:
                number: 80
        - pathType: Prefix
          path: /w
          backend:
            service:
              name: frontend-app02
              port:
                number: 80
        - pathType: Prefix
          path: /wiki
          backend:
            service:
              name: frontend-app02
              port:
                number: 80
        - pathType: Prefix
          path: /portfolio
          backend:
            service:
              name: frontend-static01
              port:
                number: 80
        #- pathType: Prefix
        #  path: /
        #  backend:
        #    service:
        #      name: frontend-static02
        #      port:
        #        number: 80
        #- pathType: Prefix
        #  path: /.*
        #  backend:
        #    service:
        #      name: frontend-static02
        #      port:
        #        number: 80
        #- pathType: Prefix
        #  path: /.*\/.*
        #  backend:
        #    service:
        #      name: frontend-static02
        #      port:
        #        number: 80

