apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  annotations:
    avp.kubernetes.io/path: "secret/data/container-registry"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: PGRvY2tlcmNvbmZpZ2pzb24+