apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  annotations:
    avp.kubernetes.io/path: "secret/data/container-registry"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjo8Z2l0bGFiX3VzZXJu
    YW1lPiwicGFzc3dvcmQiOjxnaXRsYWJfcGFzc3dvcmQ+LCJhdXRoIjo8Z2l0bGFiX2F1dGg+fSwi
    aHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjp7ImF1dGgiOjxkb2NrZXJodWJfYXV0aD59fX0=