apiVersion: v1
kind: Secret
metadata:
  name: test-registry-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/container_registry/dockerconfigjson"
type: Opaque
stringData:
  .dockerconfigjson: '<.dockerconfigjson | base64encode>'