apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  annotations:
    avp.kubernetes.io/path: "secret/data/container-registry"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {"auths":{"registry.gitlab.com":{"username":<gitlab_username>,"password":<gitlab_password>,"auth":<gitlab_auth>},"https://index.docker.io/v1/":{"auth":<dockerhub_auth>}}}