apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/container_registry"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: <cdockerconfigjson | base64encode>