apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {"auths":{"registry.gitlab.com":{"username":<path:secret/data/container-registry#gitlab_username>,"password":<path:secret/data/container-registry#gitlab_password>,"auth":<path:secret/data/container-registry#gitlab_auth>},"https://index.docker.io/v1/":{"auth":<path:secret/data/container-registry#dockerhub_auth>}}}