apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  annotations:
    avp.kubernetes.io/path: "secret/data/container-registry"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {"auths":{"registry.gitlab.com":{"username":PGdpdGxhYl91c2VybmFtZT4=,"password":PGdpdGxhYl9wYXNzd29yZD4=,"auth":PGdpdGxhYl9hdXRoPg==},"https://index.docker.io/v1/":{"auth":PGRvY2tlcmh1Yl9hdXRoPg==}}}