version: 2.1
orbs: 
  kubernetes: circleci/kubernetes@1.3.0

workflows:
  testing:
    jobs:
      - create-update:
          context: kaniko
          filters:
            branches:
              only: 
                - main
      - status-pod:
          context: kaniko
          requires:
            - create-update
          filters:
            branches:
              only: 
                - main
      - status-app:
          context: kaniko
          requires:
            - status-pod
          filters:
            branches:
              only: 
                - main
      - status-db:
          context: kaniko
          requires:
            - status-app
          filters:
            branches:
              only: 
                - main
      - delete:
          context: kaniko
          requires:
            - status-db
          filters:
            branches:
              only: 
                - main
  
executors:
  default:
    docker:
      - image: 'cimg/base:stable'
commands:
  setup_kubectl:
    steps:
      - run:
          name: "kubectl install"
          command: |
              curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/arm64/kubectl
              chmod +x ./kubectl
              sudo mv ./kubectl /usr/local/bin/kubectl
              kubectl version --client
  setup_kubeconfig:
    steps:
      - run:
          name: "kubeconfig"
          command: |
              mkdir -p ~/.kube/
              echo -n "${KUBECONFIG_DATA}" | base64 -d > ~/.kube/config
              kubectl config use-context ${CONTEXT_NAME}

jobs:
  create-update:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - setup_kubectl
      - setup_kubeconfig
      - kubernetes/create-or-update-resource:
          kustomize: true
          resource-file-path: kubernetes/overlay/testing
          show-kubectl-command: true

  status-pod:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: "status check"
          command: |
            ns=testing-aimhighergg-com
            count=3
            while true ;do 
                if [[ $(kubectl get pods -n $ns --field-selector=status.phase=Running | awk 'NR>1 {print$3}' | wc -l) -ge ${count} ]] ;then 
                    echo "pod status OK" ; sleep 3 ; break 
                else echo "pod status NG" ; sleep 3
                fi
            done

  status-app:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: "status check"
          command: |
            ns=testing-aimhighergg-com
            app=$(kubectl get pod --selector="app.kubernetes.io/name=wordpress" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n testing-aimhighergg-com exec pod/${app} -- ps aux | grep apache2 | wc -l) -ge 5  ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  status-db:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: "status check"
          command: |
            ns=testing-aimhighergg-com
            db=$(kubectl get pod --selector="app.kubernetes.io/name=mariadb-wp" -n $ns | awk 'NR>1{print $1}' | head -1)
            if [[ $(kubectl -n testing-aimhighergg-com exec pod/${db} -- ps aux | grep mysqld | wc -l) -ge 1  ]] ;then
              echo "ps status OK" 
            else
              echo "ps status NG" ; break
            fi

  delete:
    resource_class: abeyuki/circleci
    executor:
      name: default
    steps:
      - checkout
      - setup_kubectl
      - setup_kubeconfig
      - kubernetes/delete-resource:
          kustomize: true
          now: true
          resource-file-path: kubernetes/overlay/testing
          wait: true