apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-aimhighergg-com
generatorOptions:
  disableNameSuffixHash: true
namePrefix: staging-aimhighergg-com-
nameSuffix: "-001"
secretGenerator:
- name: kustomize-password
  files:
  - password=password.txt
- name: docker-registry
  files:
   - '.dockerconfigjson=docker-registry.json'
