apiVersion: v1
kind: Service
metadata:
  name: frontend-static03
  labels:
    app.kubernetes.io/name: flask-portfolio
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: flask-portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-static03
  labels:
    app.kubernetes.io/name: flask-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-portfolio
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-portfolio
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - flask-portfolio
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: flask
        image: frontend-static03
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
            cpu: "0.3"
          requests:
            memory: 256Mi
            cpu: "0.1"
        ports:
        - containerPort: 80
          name: flask
