apiVersion: v1
kind: Service
metadata:
  name: frontend-static01
  labels:
    app.kubernetes.io/name: nginx-portfolio
    app.kubernetes.io/instance: nginx-rpi-01
    app.kubernetes.io/version: "1.19"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: nginx
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: nginx-portfolio
    app.kubernetes.io/instance: nginx-rpi-01
    app.kubernetes.io/version: "1.19"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-static01
  labels:
    app.kubernetes.io/name: nginx-portfolio
    app.kubernetes.io/instance: nginx-rpi-01
    app.kubernetes.io/version: "1.19"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-portfolio
      app.kubernetes.io/instance: nginx-rpi-01
      app.kubernetes.io/version: "1.19"
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-portfolio
        app.kubernetes.io/instance: nginx-rpi-01
        app.kubernetes.io/version: "1.19"
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - nginx-portfolio
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - image: registry.gitlab.com/AbeYuki/repository/portfolio:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
