apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: wikijs-db
    app.kubernetes.io/name: wikijs
  name: wikijs-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app.kubernetes.io/component: wikijs-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-db
  labels:
    app.kubernetes.io/component: wikijs-db
    app.kubernetes.io/name: wikijs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: wikijs-db
    app.kubernetes.io/name: wikijs
  name: wikijs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: wikijs-db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: wikijs-db
        app.kubernetes.io/name: wikijs
    spec:
      containers:
      - name: wikijs-db
        image: wikijs-db
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: POSTGRES_USER
        - name: TZ
          value: "Asia/Tokyo"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: wikijs-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: wikijs-db
        persistentVolumeClaim:
          claimName: wikijs-db
