apiVersion: v1
kind: Service
metadata:
  name: frontend-static01
  labels:
    app.kubernetes.io/name: flask-portfolio
    app.kubernetes.io/instance: flask-rpi-001
    app.kubernetes.io/version: "1.19"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: flask
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: flask-portfolio
    app.kubernetes.io/instance: flask-rpi-001
    app.kubernetes.io/version: "1.19"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-static01
  labels:
    app.kubernetes.io/name: flask-portfolio
    app.kubernetes.io/instance: flask-rpi-001
    app.kubernetes.io/version: "1.19"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-portfolio
      app.kubernetes.io/instance: flask-rpi-001
      app.kubernetes.io/version: "1.19"
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-portfolio
        app.kubernetes.io/instance: flask-rpi-001
        app.kubernetes.io/version: "1.19"
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: flask
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - flask-portfolio
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: flask
        image: frontend-static03
        imagePullPolicy: Always
        env:
          - name: FLASK_APP
            value: portfolio.app:create_app()
          - name: FLASK_RUN_PORT
            value: "80"
          -name: FLASK_RUN_HOST
            value: "0.0.0.0"
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
        ports:
        - containerPort: 80
          name: flask
