apiVersion: v1
kind: Service
metadata:
  name: frontend-app02
  labels:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/instance: mediawiki-01
    app.kubernetes.io/version: "1.36.3"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: mediawiki
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/instance: mediawiki-rpi-01
    app.kubernetes.io/version: "1.36.3"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: mediawiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app02
  labels:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/instance: mediawiki-rpi-01
    app.kubernetes.io/version: "1.36.3"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mediawiki
      app.kubernetes.io/instance: mediawiki-rpi-01
      app.kubernetes.io/version: "1.36.3"
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: mediawiki
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      labels:
        environment : development
        domain: www.domain.com
        tier: frontend
        app.kubernetes.io/name: mediawiki
        app.kubernetes.io/instance: mediawiki-rpi-01
        app.kubernetes.io/version: "1.36.3"
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: mediawiki
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mediawiki
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: mediawiki   
        image: frontend-app02
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
        ports:
        - containerPort: 80
          name: mediawiki