apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: wikijs
    app.kubernetes.io/name: wikijs
  name: wikijs
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: wikijs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: wikijs
    app.kubernetes.io/name: wikijs
  name: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wikijs
  template:
    metadata:
      labels:
        app.kubernetes.io/component: wikijs
        app.kubernetes.io/name: wikijs
    spec:
      containers:
      - name: wikijs
        image: wikijs
        ports:
        - containerPort: 3000
        env:
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: DB_TYPE
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: DB_NAME
        - name: TZ
          value: "Asia/Tokyo"