apiVersion: v1
kind: Service
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: wordpress
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: wordpress
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
      app.kubernetes.io/instance: wordpress-001
      app.kubernetes.io/version: "5.5"
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: wordpress
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
        app.kubernetes.io/instance: wordpress-001
        app.kubernetes.io/version: "5.5"
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: wordpress
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - wordpress
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: wordpress
        image: frontend-app01
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: WORDPRESS_DB_NAME
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html
      volumes:
      - name: wordpress
        persistentVolumeClaim:
          claimName: frontend-app01
