apiVersion: v1
kind: Service
metadata:
  name: backend-db02
  labels:
    app.kubernetes.io/name: mariadb-mw
    app.kubernetes.io/instance: mariadb-001
    app.kubernetes.io/version: "10.5"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mediawiki
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mariadb-mw
    app.kubernetes.io/instance: mariadb-001
    app.kubernetes.io/version: "10.5"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mediawiki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db02
  labels:
    app.kubernetes.io/name: mariadb-mw
    app.kubernetes.io/instance: mariadb-001
    app.kubernetes.io/version: "10.5"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mediawiki
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db02
  labels:
    app.kubernetes.io/name: mariadb-mw
    app.kubernetes.io/instance: mariadb-001
    app.kubernetes.io/version: "10.5"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb-mw
      app.kubernetes.io/instance: mariadb-001
      app.kubernetes.io/version: "10.5"
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: mediawiki
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb-mw
        app.kubernetes.io/instance: mariadb-001
        app.kubernetes.io/version: "10.5"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: mediawiki
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mariadb-mw
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: db02
        image: backend-db02
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 512Mi
            cpu: "0.25"
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password   
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: MYSQL_DATABASE_MW
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: MYSQL_USER_MW               
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: backend-db02