apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-aimhighergg-com
bases:
  - ../../base
  - ../../base-ingress
  - secret-avp-db.yaml
configMapGenerator:
- name: template-config
  literals:
  - WORDPRESS_DB_HOST=backend-db01
  - WORDPRESS_DB_NAME=wordpress
  - WORDPRESS_DB_USER=wordpress
  - MYSQL_DATABASE_WP=wordpress
  - MYSQL_USER_WP=wordpress
  - MYSQL_USER_MW=wordpress
  - MYSQL_DATABASE_MW=tips_wiki
  - DB_HOST=staging-aimhighergg-com-wikijs-db-001
  - DB_PORT="5432"
  - DB_TYPE=postgres
  - PGDATA=/var/lib/postgresql/data/pgdata
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
images:
  - name: frontend-app01
    newName: wordpress
    newTag: "6.0.0-php8.1-apache"
  - name: backend-db01
    newName: mariadb
    newTag: "10.5"
  - name: frontend-static03
    newName: registry.gitlab.com/aimhighergg/docker-registry/portfolio
    newTag: "1.2.1"
  - name: wikijs-db
    newName: postgres
    newTag: "15-alpine"
  - name: wikijs
    newName: ghcr.io/requarks/wiki
    newTag: "2"
replicas:
- name: frontend-app01
  count: 1
- name: backend-db01
  count: 1
- name: frontend-static03
  count: 1
- name: wikijs
  count: 1
- name: wikijs-db
  count: 1
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: backend-db01
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.25"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.5"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: frontend-app01
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.25"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "125Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.5"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: backend-db02
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "125Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.3"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: frontend-app02
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "125Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.3"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: frontend-static01
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "125Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "125Mi"
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: frontend-static02
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "125Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "125Mi"
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: frontend-static03
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "0.1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "0.3"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "526Mi"
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: frontend-app01
    patch: |-
      - op: replace
        path: /spec/accessModes/0
        value: ReadWriteOnce
      - op: replace
        path: /spec/storageClassName
        value: longhorn
      - op: replace
        path: /spec/resources/requests/storage
        value: "1Gi"
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: backend-db01
    patch: |-
      - op: replace
        path: /spec/accessModes/0
        value: ReadWriteOnce
      - op: replace
        path: /spec/storageClassName
        value: longhorn
      - op: replace
        path: /spec/resources/requests/storage
        value: "1Gi"
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: wikijs-db
    patch: |-
      - op: replace
        path: /spec/accessModes/0
        value: ReadWriteOnce
      - op: replace
        path: /spec/storageClassName
        value: longhorn
      - op: replace
        path: /spec/resources/requests/storage
        value: "1Gi"
  - target:
      version: v1
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-issuer
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: aim4highergg@gmail.com
      - op: replace
        path: /spec/acme/server
        value: https://acme-v02.api.letsencrypt.org/directory
      - op: replace
        path: /spec/acme/privateKeySecretRef/name
        value: cluster-issuer-secret
      - op: replace
        path: /spec/acme/solvers/0/http01/ingress/class
        value: nginx
  - target:
      version: v1
      group: networking.k8s.io
      name: ingress-tls
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-tls
      spec:
        ingressClassName: nginx 
        tls:
        - hosts:
            - staging.aimhighergg.com
          secretName: tls-secret
        rules:
        - host: staging.aimhighergg.com
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: frontend-app01
                  port:
                    number: 80
            - pathType: Prefix
              path: /portfolio
              backend:
                service:
                  name: frontend-static03
                  port:
                    number: 80
  - target:
      version: v1
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-issuer-wiki
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: aim4highergg@gmail.com
      - op: replace
        path: /spec/acme/server
        value: https://acme-v02.api.letsencrypt.org/directory
      - op: replace
        path: /spec/acme/privateKeySecretRef/name
        value: cluster-issuer-secret-wiki
      - op: replace
        path: /spec/acme/solvers/0/http01/ingress/class
        value: nginx
  - target:
      version: v1
      group: networking.k8s.io
      name: ingress-tls-wiki
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-tls-wiki
      spec:
        ingressClassName: nginx 
        tls:
        - hosts:
            - staging-wiki.aimhighergg.com
          secretName: tls-secret-wiki
        rules:
        - host: staging-wiki.aimhighergg.com
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: wikijs
                  port:
                    number: 80
